/**
 * Generate Carousel HTML Template
 * 
 * Creates a modern, gradient-based HTML carousel template for social media posts.
 * Designed for Instagram-style 1080x1080px posts.
 * 
 * Usage:
 *   npx ts-node scripts/generate-carousel-html.ts --topic "AI Tips" --slides 5
 *   npx ts-node scripts/generate-carousel-html.ts --topic "Tech News" --interactive
 */

interface SlideData {
  title?: string
  text?: string
  list?: string[]
  image?: string
  background?: string
}

interface CarouselOptions {
  topic: string
  slides: SlideData[]
  width?: number
  height?: number
  outputPath?: string
}

// Gradient presets
const GRADIENTS = [
  'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', // Purple
  'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', // Pink
  'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', // Blue
  'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', // Green
  'linear-gradient(135deg, #fa709a 0%, #fee140 100%)', // Sunset
  'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)', // Pastel
  'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)', // Rose
  'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)', // Peach
]

// Color palettes
const COLORS = [
  { bg: '#667eea', text: '#ffffff' },
  { bg: '#f5576c', text: '#ffffff' },
  { bg: '#4facfe', text: '#ffffff' },
  { bg: '#43e97b', text: '#0a0a0a' },
  { bg: '#fa709a', text: '#ffffff' },
  { bg: '#fee140', text: '#0a0a0a' },
]

/**
 * Generate slides HTML from slide data
 */
function generateSlidesHtml(slides: SlideData[]): string {
  return slides.map((slide, index) => {
    const gradient = slide.background || GRADIENTS[index % GRADIENTS.length]
    
    return `
    <div class="slide" data-slide="${index + 1}">
      <div class="slide-bg" style="background: ${gradient}"></div>
      <div class="slide-badge">${index + 1}/${slides.length}</div>
      <div class="slide-content">
        ${slide.title ? `<h2 class="slide-title">${slide.title}</h2>` : ''}
        ${slide.text ? `<p class="slide-text">${slide.text}</p>` : ''}
        ${slide.list && slide.list.length > 0 ? `
          <ul class="slide-list">
            ${slide.list.map(item => `<li>${item}</li>`).join('')}
          </ul>
        ` : ''}
      </div>
      ${slide.image ? `<div class="slide-image" style="background-image: url('${slide.image}')"></div>` : ''}
      <div class="slide-footer">Generated by Merry Dashboard</div>
    </div>
    `
  }).join('')
}

/**
 * Generate complete HTML carousel document
 */
export function generateCarouselHtml(options: CarouselOptions): string {
  const { topic, slides, width = 1080, height = 1080 } = options
  
  const slidesHtml = generateSlidesHtml(slides)

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${topic} - Social Carousel</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      background: #0a0a0a;
      color: white;
      overflow-x: hidden;
    }
    
    .carousel {
      width: 100vw;
      height: 100vh;
      position: relative;
    }
    
    .slide {
      width: 100vw;
      height: 100vh;
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
    }
    
    .slide-bg {
      position: absolute;
      inset: 0;
      z-index: 1;
    }
    
    .slide-badge {
      position: absolute;
      top: 40px;
      right: 40px;
      z-index: 100;
      background: rgba(0, 0, 0, 0.3);
      backdrop-filter: blur(10px);
      padding: 10px 20px;
      border-radius: 30px;
      font-size: 18px;
      font-weight: 600;
      letter-spacing: 1px;
    }
    
    .slide-content {
      position: relative;
      z-index: 10;
      max-width: 80%;
      text-align: center;
      padding: 40px;
    }
    
    .slide-title {
      font-size: ${width > 800 ? '72px' : '48px'};
      font-weight: 900;
      line-height: 1.1;
      margin-bottom: 30px;
      text-shadow: 0 4px 30px rgba(0, 0, 0, 0.3);
      letter-spacing: -2px;
    }
    
    .slide-text {
      font-size: ${width > 800 ? '32px' : '24px'};
      line-height: 1.6;
      opacity: 0.95;
      max-width: 700px;
      margin: 0 auto;
    }
    
    .slide-list {
      list-style: none;
      margin-top: 40px;
      text-align: left;
      display: inline-block;
    }
    
    .slide-list li {
      font-size: ${width > 800 ? '28px' : '22px'};
      margin: 20px 0;
      padding-left: 50px;
      position: relative;
      line-height: 1.4;
    }
    
    .slide-list li::before {
      content: '';
      position: absolute;
      left: 0;
      top: 50%;
      transform: translateY(-50%);
      width: 30px;
      height: 30px;
      background: rgba(255, 255, 255, 0.3);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    
    .slide-list li::after {
      content: '✓';
      position: absolute;
      left: 8px;
      top: 50%;
      transform: translateY(-50%);
      font-size: 16px;
      font-weight: bold;
    }
    
    .slide-image {
      position: absolute;
      inset: 0;
      background-size: cover;
      background-position: center;
      opacity: 0.15;
      z-index: 5;
    }
    
    .slide-footer {
      position: absolute;
      bottom: 30px;
      left: 50%;
      transform: translateX(-50%);
      z-index: 100;
      font-size: 14px;
      opacity: 0.4;
      letter-spacing: 2px;
      text-transform: uppercase;
    }
    
    /* Decorative elements */
    .slide::before {
      content: '';
      position: absolute;
      width: 600px;
      height: 600px;
      border-radius: 50%;
      background: rgba(255, 255, 255, 0.1);
      filter: blur(100px);
      z-index: 2;
      pointer-events: none;
    }
    
    .slide:nth-child(odd)::before {
      top: -200px;
      right: -200px;
    }
    
    .slide:nth-child(even)::before {
      bottom: -200px;
      left: -200px;
    }
    
    /* Print styles for static export */
    @media print {
      .slide {
        page-break-after: always;
        width: 100%;
        height: 100vh;
      }
    }
  </style>
</head>
<body>
  <div class="carousel">
    ${slidesHtml}
  </div>
</body>
</html>`
}

/**
 * Generate default slides for a topic
 */
export function generateDefaultSlides(topic: string, count = 5): SlideData[] {
  const templates: SlideData[] = [
    {
      title: topic,
      text: 'The complete guide you need',
      background: GRADIENTS[0]
    },
    {
      title: 'Why This Matters',
      text: 'Understanding the fundamentals will change everything',
      background: GRADIENTS[1]
    },
    {
      title: 'Key Insights',
      list: [
        'First important point',
        'Second crucial detail',
        'Third major takeaway'
      ],
      background: GRADIENTS[2]
    },
    {
      title: 'How to Get Started',
      list: [
        'Step 1: Begin here',
        'Step 2: Build momentum',
        'Step 3: See results'
      ],
      background: GRADIENTS[3]
    },
    {
      title: topic,
      text: 'Start your journey today! 🚀',
      background: GRADIENTS[4]
    }
  ]

  return templates.slice(0, count)
}

// CLI interface
if (require.main === module) {
  const args = process.argv.slice(2)
  
  // Parse arguments
  let topic = 'Social Media Post'
  let slideCount = 5
  let outputPath: string | undefined

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--topic' && args[i + 1]) {
      topic = args[i + 1]
      i++
    } else if (args[i] === '--slides' && args[i + 1]) {
      slideCount = parseInt(args[i + 1]) || 5
      i++
    } else if (args[i] === '--output' && args[i + 1]) {
      outputPath = args[i + 1]
      i++
    } else if (args[i] === '--help' || args[i] === '-h') {
      console.log(`
Carousel HTML Generator

Usage:
  npx ts-node scripts/generate-carousel-html.ts [options]

Options:
  --topic <text>     Set the main topic/title (default: "Social Media Post")
  --slides <number>  Number of slides to generate (default: 5)
  --output <path>    Save to file path instead of stdout
  --help, -h         Show this help message

Examples:
  npx ts-node scripts/generate-carousel-html.ts --topic "AI Tips" --slides 4
  npx ts-node scripts/generate-carousel-html.ts --output carousel.html
      `)
      process.exit(0)
    }
  }

  // Generate carousel
  const slides = generateDefaultSlides(topic, slideCount)
  const html = generateCarouselHtml({ topic, slides })

  if (outputPath) {
    const fs = require('fs')
    fs.writeFileSync(outputPath, html)
    console.log(`✅ Carousel saved to: ${outputPath}`)
    console.log(`   Slides: ${slideCount}`)
    console.log(`   Topic: ${topic}`)
  } else {
    console.log(html)
  }
}

export default generateCarouselHtml
